[build-system]
requires = ["setuptools>=61", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gulp"
dynamic = ["version"]
authors = [{ name = "Mentat", email = "info@mentat.is" }]
description = "gULP - (generic) Unified Log Processor."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "aiocsv==1.3.2",
    "aiosmtplib==3.0.2",
    "asyncio-pool==0.6.0",
    "certifi==2024.8.30",
    "charset-normalizer==3.3.2",
    "dotwiz==0.4.0",
    "elasticsearch[async]==8.15.1",
    "evtx==0.8.6",
    "fastapi==0.115.5",
    "idna==3.10",
    "Jinja2==3.1.4",
    "MarkupSafe==2.1.5",
    "muty@git+https://github.com/mentat-is/muty-python@refactor",
    "opensearch-py==2.7.1",
    "packaging==24.1",
    "pip",
    "psycopg_pool==3.2.3",
    "psycopg-binary==3.2.2",
    "psycopg==3.2.2",
    "pydantic==2.9.2",
    "pyparsing==3.1",
    "pySigma-backend-elasticsearch==1.1.3",
    "pySigma-backend-opensearch==1.0.3",
    "pySigma==0.11.14",
    "python-multipart==0.0.9",
    "python-pip==1.1.1",
    "PyYAML==6.0.2",
    "requests_toolbelt==1.0.0",
    "requests==2.32.3",
    "setuptools==75.1.0",
    "sigma-cli==1.0.4",
    "sqlalchemy-dlock==0.6.1.post1",
    "sqlalchemy-mixins==2.0.5",
    "sqlalchemy-utils==0.41.2",
    "sqlalchemy[asyncio]==2.0.34",
    "starlette==0.41.2",
    "urllib3==2.2.3",
    "uvicorn==0.30.6",
    "websockets==13.0.1",
]

[project.scripts]
gulp = "gulp.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
