[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gulp"
dynamic = ["dependencies", "optional-dependencies"]
authors = [{ name = "Mentat", email = "info@mentat.is" }]
description = "gULP - (generic) Unified Log Processor."
readme = "README.md"
requires-python = ">=3.12"
version = "2025.01.01"

[project.scripts]
gulp = "gulp.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}

